using Pdf2Hwp.Core;
using Pdf2Hwp.Infrastructure;

namespace Pdf2Hwp.Tests;

public sealed class ApplicationServicesTests
{
    [Fact] public void Output_name_collision_is_safe() { using var d = new TempDirectory(); File.WriteAllText(Path.Combine(d.Path, "a_converted.hwpx"), "x"); Assert.EndsWith("a_converted_2.hwpx", OutputNamingPolicy.Choose(d.Path, "a.pdf")); }
    [Fact] public void Settings_round_trip_and_corrupt_fallback() { using var d = new TempDirectory(); var store = new JsonSettingsStore(Path.Combine(d.Path, "settings.json")); var expected = new AppSettings(d.Path, RenderQuality.High, 900, 700, "Normal", false); store.Save(expected); Assert.Equal(expected, store.Load()); File.WriteAllText(Path.Combine(d.Path, "settings.json"), "{"); Assert.Equal(new AppSettings(), store.Load()); }
    [Fact] public void Recent_files_are_bounded_and_missing_files_are_ignored() { using var d = new TempDirectory(); var existing = Path.Combine(d.Path, "a.pdf"); File.WriteAllText(existing, "x"); var store = new RecentFilesStore(Path.Combine(d.Path, "recent.json"), 2); store.Add(existing); store.Add(Path.Combine(d.Path, "missing.pdf")); Assert.Single(store.Load()); }
    [Fact] public void Temp_workspace_is_cleaned_after_dispose() { var factory = new TempWorkspaceManager(); var workspace = factory.Create(); var path = workspace.DirectoryPath; Assert.True(Directory.Exists(path)); workspace.Dispose(); Assert.False(Directory.Exists(path)); }
    [Fact] public void Conversion_workspace_cleanup_skips_live_pid_and_removes_stale_dead_pid()
    {
        var factory = new ConversionWorkspaceFactory(); using var live = factory.Create(); var livePath = live.DirectoryPath; Directory.SetLastWriteTimeUtc(livePath, DateTime.UtcNow.AddDays(-10)); Assert.Equal(0, factory.CleanupStale(TimeSpan.FromDays(7))); Assert.True(Directory.Exists(livePath));
        live.Dispose(); using var stale = factory.Create(); var stalePath = stale.DirectoryPath; File.WriteAllText(Path.Combine(stalePath, ".active"), "pid=-1\nstarted=2020-01-01T00:00:00Z"); Directory.SetLastWriteTimeUtc(stalePath, DateTime.UtcNow.AddDays(-10)); Assert.Equal(1, factory.CleanupStale(TimeSpan.FromDays(7))); Assert.False(Directory.Exists(stalePath));
    }
    [Fact] public void Conversion_history_is_bounded_and_clearable() { using var d = new TempDirectory(); var store = new ConversionHistoryStore(Path.Combine(d.Path, "history.json"), 2); for (var i = 0; i < 3; i++) store.Add(new(DateTimeOffset.UtcNow, [$"p{i}"], $"o{i}", i, RenderQuality.Standard, TimeSpan.Zero, ConversionJobStatus.Completed, "0.1.0")); Assert.Equal(2, store.Load().Count); store.Clear(); Assert.Empty(store.Load()); }
    [Fact] public void Failed_and_cancelled_history_are_kept_without_assuming_output_exists_and_clear_preserves_output() { using var d = new TempDirectory(); var source = Path.Combine(d.Path, "source.pdf"); File.WriteAllText(source, "source"); var output = Path.Combine(d.Path, "result.hwpx"); File.WriteAllText(output, "output"); var store = new ConversionHistoryStore(Path.Combine(d.Path, "history.json")); store.Add(new(DateTimeOffset.UtcNow, ["source.pdf"], Path.Combine(d.Path, "missing.hwpx"), 1, RenderQuality.Standard, TimeSpan.Zero, ConversionJobStatus.Cancelled, "0.1.0", [new(source, 0)])); store.Add(new(DateTimeOffset.UtcNow, ["source.pdf"], output, 1, RenderQuality.Standard, TimeSpan.Zero, ConversionJobStatus.Failed, "0.1.0", [new(source, 0)])); var entries = store.Load(); Assert.Contains(entries, e => e.Status == ConversionJobStatus.Cancelled && !File.Exists(e.OutputPath) && e.CanRetry); Assert.Contains(entries, e => e.Status == ConversionJobStatus.Failed && e.CanRetry); store.Clear(); Assert.Empty(store.Load()); Assert.Equal("output", File.ReadAllText(output)); }
    [Fact] public void Settings_save_is_atomic_and_leaves_no_partial_file() { using var d = new TempDirectory(); var path = Path.Combine(d.Path, "settings.json"); new JsonSettingsStore(path).Save(new(d.Path)); Assert.False(Directory.GetFiles(d.Path, "*.partial-*", SearchOption.TopDirectoryOnly).Any()); Assert.True(File.Exists(path)); }
    [Fact] public async Task Concurrent_settings_writes_leave_one_valid_atomic_document() { using var d = new TempDirectory(); var path = Path.Combine(d.Path, "settings.json"); await Task.WhenAll(Enumerable.Range(0, 12).Select(i => Task.Run(() => new JsonSettingsStore(path).Save(new AppSettings($"folder-{i}", (i % 2) == 0 ? RenderQuality.Standard : RenderQuality.High))))); var final = new JsonSettingsStore(path).Load(); Assert.StartsWith("folder-", final.LastOutputDirectory); Assert.False(Directory.GetFiles(d.Path, "*.partial-*", SearchOption.TopDirectoryOnly).Any()); }
    [Fact] public async Task Concurrent_history_updates_remain_valid_and_keep_entries() { using var d = new TempDirectory(); var store = new ConversionHistoryStore(Path.Combine(d.Path, "history.json"), 50); await Task.WhenAll(Enumerable.Range(0, 24).Select(i => Task.Run(() => store.Add(new(DateTimeOffset.UtcNow, [$"s{i}"], $"o{i}", 1, RenderQuality.Standard, TimeSpan.Zero, ConversionJobStatus.Completed, "0.1.0"))))); Assert.Equal(24, store.Load().Count); }
    [Fact] public async Task Preview_cache_reports_size_and_respects_limit_without_removing_leased_entries() { using var d = new TempDirectory(); var cache = new PreviewThumbnailCache(d.Path); var old = cache.GetPath("old", 0, 300); var current = cache.GetPath("current", 0, 300); Directory.CreateDirectory(Path.GetDirectoryName(old)!); Directory.CreateDirectory(Path.GetDirectoryName(current)!); File.WriteAllBytes(old, new byte[8]); File.WriteAllBytes(current, new byte[8]); File.SetLastAccessTimeUtc(old, DateTime.UtcNow.AddDays(-2)); Assert.Equal((2, 16L), cache.Measure()); using var lease = await cache.AcquireEntryAsync(current, CancellationToken.None); Assert.True(cache.Cleanup(8) >= 1); Assert.True(File.Exists(current)); Assert.Equal(8, cache.Measure().Bytes); }
    [Fact] public async Task Preview_cache_clear_skips_entries_held_by_active_reader() { using var d = new TempDirectory(); var cache = new PreviewThumbnailCache(d.Path); var path = cache.GetPath("current", 0, 300); Directory.CreateDirectory(Path.GetDirectoryName(path)!); File.WriteAllBytes(path, new byte[8]); using var lease = await cache.AcquireEntryAsync(path, CancellationToken.None); cache.Clear(); Assert.True(File.Exists(path)); }
    private sealed class TempDirectory : IDisposable { public string Path { get; } = System.IO.Path.Combine(System.IO.Path.GetTempPath(), Guid.NewGuid().ToString("N")); public TempDirectory() => Directory.CreateDirectory(Path); public void Dispose() { try { Directory.Delete(Path, true); } catch { } } }
}
